// A collection of quotes of varying length and difficulty for typing races
export const QUOTES: string[] = [
  "The quick brown fox jumps over the lazy dog.",
  "To be or not to be, that is the question.",
  "All that glitters is not gold.",
  "In the middle of every difficulty lies opportunity.",
  "It always seems impossible until it is done.",
  "Life is what happens when you are busy making other plans.",
  "The only way to do great work is to love what you do.",
  "Success is not final, failure is not fatal, it is the courage to continue that counts.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Do not watch the clock, do what it does and keep going.",
  "Believe you can and you are halfway there.",
  "Everything you have ever wanted is on the other side of fear.",
  "The best time to plant a tree was twenty years ago, the second best time is now.",
  "You miss one hundred percent of the shots you do not take.",
  "Whether you think you can or think you cannot, you are right.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "In three words I can sum up everything I have learned about life: it goes on.",
  "To handle yourself use your head, to handle others use your heart.",
  "You only live once, but if you do it right, once is enough.",
  "Spread love everywhere you go, let no one ever come to you without leaving happier.",
  "When you reach the end of your rope, tie a knot in it and hang on.",
  "Always remember that you are absolutely unique, just like everyone else.",
  "Do not go where the path may lead, go instead where there is no path and leave a trail.",
  "You will face many defeats in life, but never let yourself be defeated.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "In the end, it is not the years in your life that count, it is the life in your years.",
  "Never let the fear of striking out keep you from playing the game.",
  "Life is either a daring adventure or nothing at all.",
  "Many of life's failures are people who did not realize how close they were to success.",
  "You have brains in your head and feet in your shoes, you can steer yourself any direction you choose.",

  // Programming and technology quotes
  "Any fool can write code that a computer can understand, good programmers write code that humans can understand.",
  "First, solve the problem, then write the code.",
  "Experience is the name everyone gives to their mistakes.",
  "In order to be irreplaceable, one must always be different.",
  "Java is to JavaScript what car is to carpet.",
  "Knowledge is power and enthusiasm pulls the switch.",
  "Sometimes it pays to stay in bed on Monday rather than spending the rest of the week debugging.",
  "Simplicity is the soul of efficiency.",
  "Before software can be reusable it first has to be usable.",
  "Make it work, make it right, make it fast.",

  // Short and punchy for beginners
  "Code is like humor, when you have to explain it, it is bad.",
  "Fix the cause, not the symptom.",
  "Optimism is an occupational hazard of programming, feedback is the treatment.",
  "When in doubt, leave it out.",
  "Talk is cheap, show me the code.",

  // Longer quotes for advanced typists
  "The most damaging phrase in the language is we have always done it this way, because it closes the mind to new possibilities and better approaches.",
  "There are two ways of constructing a software design: one way is to make it so simple that there are obviously no deficiencies, and the other way is to make it so complicated that there are no obvious deficiencies.",
  "The computing scientist's main challenge is not to get confused by the complexities of his own making.",
  "Programs must be written for people to read, and only incidentally for machines to execute.",
  "The most important property of a program is whether it accomplishes the intention of its user.",
  "Measuring programming progress by lines of code is like measuring aircraft building progress by weight.",
  "The function of good software is to make the complex appear to be simple.",
  "Good code is its own best documentation, as you are about to add a comment, ask yourself, how can I improve the code so that this comment is not needed.",
  "One of the best programming skills you can have is knowing when to walk away for a while and let your subconscious work on a problem.",
  "The best programmers are not marginally better than merely good ones, they are an order of magnitude better, measured by whatever standard you care to use.",
  "Debugging is twice as hard as writing the code in the first place, therefore if you write the code as cleverly as possible, you are by definition not smart enough to debug it.",
  "The most expensive thing in software is not building the wrong thing, it is maintaining the wrong thing for years after you realize it was wrong.",
  "Software is a great combination of artistry and engineering, when the real software engineering happens, it will be like anything else, done by artists.",
  "There is no silver bullet that will reduce the effort of software projects by an order of magnitude, the only way to make it happen is a series of small improvements over time.",
  "Every great developer you know got there by solving problems they were unqualified to solve until they actually did it.",
];